"""
How many distinct terms are in the sequence generated by 
a^b for 2 <= a <= 100 and 2 <= b <= 100?
"""
import math

distincts = []

for a in range(2,101):
	for b in range(2,101):
		term = math.pow(a,b)
		if term not in distincts:
			distincts.append(term)
			print("new distinct: %s", term)

print ("Total terms: %s" % len(distincts))