"""
Each new term in the Fibonacci sequence is generated by adding
the previous two terms. By starting with 1 and 2, the first 10
terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms.
"""
first_num = 0
second_num = 1
total=0
run = True
while run == True:
	new_num = first_num + second_num
	if new_num > 4000000:
		break;

	if new_num%2 == 0: #is new number even?
		total += new_num

	first_num = second_num
	second_num = new_num

print(total)